apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrum-ai-router
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.example.yaml
  - networkpolicy.yaml
  - pdb.yaml
