apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrum-ai-router-state
  labels:
    app.kubernetes.io/name: metrum-ai-router
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
