apiVersion: v1
kind: Service
metadata:
  name: smart-llmrouter
  labels:
    app.kubernetes.io/name: smart-llmrouter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smart-llmrouter
  ports:
    - name: http
      port: 80
      targetPort: http
