apiVersion: v1
kind: Service
metadata:
  name: metrum-ai-router
  labels:
    app.kubernetes.io/name: metrum-ai-router
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metrum-ai-router
  ports:
    - name: http
      port: 80
      targetPort: http
