apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrum-ai-router
resources:
  - ../../base
  - serving/vllm-tiny-deployment.yaml
  - serving/vllm-tiny-service.yaml
  - serving/vllm-chat-deployment.yaml
  - serving/vllm-chat-service.yaml
  - serving/vllm-coder-deployment.yaml
  - serving/vllm-coder-service.yaml
patches:
  - path: patch-image.yaml
  - path: networkpolicy-patch.yaml
