/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  routerSidebar: [
    "overview",
    "concepts",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/hosted-quickstart",
        "getting-started/available-models",
        "getting-started/codex-cli",
        "getting-started/claude-code-cli",
      ],
    },
    {
      type: "category",
      label: "Installation",
      collapsed: false,
      items: [
        "installation/index",
        "installation/docker-compose",
        "installation/binary",
        "operations/deployment",
      ],
    },
    {
      type: "category",
      label: "Commercial Access And Licensing",
      collapsed: false,
      items: [
        "licensing/deployment-paths",
        "licensing/index",
        "licensing/evaluation-pilot",
        "licensing/renewal",
        "licensing/enterprise-private-managed",
        "licensing/billing-enforcement",
        "operations/license-protected-deployments",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      collapsed: false,
      items: [
        "configuration/router-config",
        "configuration/admin-authentication",
        "configuration/admin-authorization",
        "configuration/pii-filtering",
      ],
    },
    {
      type: "category",
      label: "Routing",
      collapsed: false,
      items: [
        "routing/overview",
        "configuration/model-group-contracts",
        "configuration/reasoning-routing",
        "configuration/dynamic-score-routing",
        "configuration/routing-typescript",
        "configuration/external-routing-policy",
      ],
    },
    {
      type: "category",
      label: "Providers And Models",
      collapsed: false,
      items: [
        "providers-models/overview",
        "reference/model-metadata",
        "reference/add-provider-model",
        "configuration/self-hosted-upstreams",
      ],
    },
    {
      type: "category",
      label: "API Compatibility",
      collapsed: false,
      items: [
        "reference/api-compatibility",
        "reference/errors",
      ],
    },
    {
      type: "category",
      label: "Agents, Tools, And Vision",
      collapsed: false,
      items: [
        "agents-tools-vision/overview",
        "getting-started/codex-cli",
        "getting-started/claude-code-cli",
        "configuration/image-analysis-vlm",
        "agents-tools-vision/structured-outputs",
      ],
    },
    {
      type: "category",
      label: "Usage, Cost, And Reports",
      collapsed: false,
      items: [
        "usage-cost-reports/overview",
        "operations/usage-reporting",
        "operations/admin-browser-reports",
        "operations/report-examples",
        "evaluation/cost-governance",
      ],
    },
    {
      type: "category",
      label: "Security And Governance",
      collapsed: false,
      items: [
        "security-governance/overview",
        "evaluation/security-and-trust",
        "configuration/admin-authentication",
        "configuration/admin-authorization",
        "configuration/pii-filtering",
        "evaluation/deployment-security-assessment",
      ],
    },
    {
      type: "category",
      label: "Operations",
      collapsed: false,
      items: [
        "operations/deployment-patterns",
        "operations/observability",
        "operations/key-generation",
        "evaluation/deployment-readiness",
        "evaluation/operational-acceptance",
      ],
    },
    {
      type: "category",
      label: "Troubleshooting",
      collapsed: false,
      items: [
        "troubleshooting/index",
        "troubleshooting/requests",
        "troubleshooting/licensing",
        "reference/errors",
      ],
    },
    {
      type: "category",
      label: "Evaluation And Case Studies",
      collapsed: false,
      items: [
        "evaluation/overview",
        "evaluation/evaluate-smart-router",
        "evaluation/prove-router-quality",
        "evaluation/product-capabilities",
        "evaluation/harbor-case-study",
        "evaluation/model-group-quality",
      ],
    },
    "evaluation/commercial-evaluation",
    "evaluation/competitive-landscape",
    "solution-brief",
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: [
        "reference/api-compatibility",
        "reference/errors",
        "reference/model-metadata",
        "reference/add-provider-model",
      ],
    },
    {
      type: "category",
      label: "Release Notes And Upgrades",
      collapsed: false,
      items: [
        "release-notes/index",
        "release-notes/upgrade-guide",
      ],
    },
  ],
};

module.exports = sidebars;
