/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  routerSidebar: [
    "overview",
    {
      type: "category",
      label: "Tutorials",
      collapsed: false,
      items: [
        "getting-started/hosted-quickstart",
        "getting-started/codex-cli",
        "getting-started/claude-code-cli",
        "getting-started/coding-agent-clients",
      ],
    },
    {
      type: "category",
      label: "How-To",
      collapsed: false,
      items: [
        "installation/index",
        "installation/deployment-artifacts",
        "installation/docker-compose",
        "installation/binary",
        "installation/kubernetes",
        "installation/package-validation",
        "reference/add-provider-model",
        "operations/key-generation",
        "configuration/pii-filtering",
        "configuration/dynamic-score-routing",
        "configuration/routing-typescript",
        "configuration/external-routing-policy",
        "configuration/image-analysis-vlm",
        "configuration/reasoning-routing",
        "configuration/self-hosted-upstreams",
        "operations/usage-reporting",
        "operations/admin-browser-reports",
        "troubleshooting/index",
        "troubleshooting/requests",
        "troubleshooting/licensing",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: false,
      items: [
        "faq",
        "getting-started/available-models",
        "reference/api-compatibility",
        "reference/errors",
        "reference/diagnostics-schema",
        "reference/model-metadata",
        "configuration/router-config",
        "configuration/license",
        "configuration/provider-catalog",
        "configuration/provider-traffic-shaping",
        "configuration/model-groups",
        "configuration/caller-tokens",
        "configuration/caller-traffic-shaping",
        "configuration/cache-usage-store",
        "configuration/admin-authentication",
        "configuration/admin-authorization",
        "concepts/glossary",
      ],
    },
    {
      type: "category",
      label: "Explanation",
      collapsed: false,
      items: [
        "concepts",
        "routing/strategy-decision-tree",
        "routing/overview",
        "routing/customer-controlled-routing",
        "configuration/model-group-contracts",
        "agents-tools-vision/overview",
        "agents-tools-vision/structured-outputs",
        "providers-models/overview",
        "usage-cost-reports/overview",
        "security-governance/overview",
        "evaluation/overview",
        "evaluation/evaluate-smart-router",
        "evaluation/prove-router-quality",
        "evaluation/model-group-quality",
        "evaluation/product-capabilities",
        "evaluation/cost-governance",
        "evaluation/deployment-readiness",
        "evaluation/deployment-security-assessment",
        "evaluation/operational-acceptance",
        "evaluation/security-and-trust",
        "evaluation/commercial-evaluation",
        "evaluation/competitive-landscape",
        "evaluation/enterprise-faq",
        "evaluation/harbor-case-study",
        "solution-brief",
      ],
    },
    {
      type: "category",
      label: "Commercial Access And Licensing",
      collapsed: false,
      items: [
        "licensing/deployment-paths",
        "licensing/index",
        "licensing/evaluation-pilot",
        "licensing/renewal",
        "licensing/enterprise-private-managed",
        "licensing/billing-enforcement",
        "operations/license-protected-deployments",
      ],
    },
    {
      type: "category",
      label: "Operations",
      collapsed: false,
      items: [
        "operations/deployment-patterns",
        "operations/production-promotion",
        "operations/observability",
        "operations/report-examples",
      ],
    },
    {
      type: "category",
      label: "Release Notes And Upgrades",
      collapsed: false,
      items: [
        "release-notes/index",
        "release-notes/upgrade-guide",
        { type: "link", label: "Releases Index", href: "/docs/releases" },
      ],
    },
  ],
};

module.exports = sidebars;
